// preact/demo/src/components/demos/ChipDemo.tsx
import { h } from 'preact';
import { Chip } from '@material-design/preact';

export function ChipDemo() {
    return <div>
        <h2 class="umd-type--display-1">Chips</h2>
        <div style="display: flex">
            <Chip>Example Chip</Chip>
            <Chip image="http://placehold.it/64x64">James Birtles</Chip>
        </div>
    </div>
}

// angular/demo/src/app/demos/chip/chip-demo.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'chip-demo',
    templateUrl: './chip-demo.component.html',
})
export class ChipDemoComponent {
}

<h2 class="umd-type--display-1">Chips</h2>
<div style="display: flex">
    <mda-chip>Example Chip</mda-chip>
    <mda-chip image="http://placehold.it/64x64">James Birtles</mda-chip>
</div>
