// angular/demo/src/app/demos/ripple/ripple-demo.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'ripple-demo',
    templateUrl: './ripple-demo.component.html',
})
export class RippleDemoComponent {
}

<h2 class="umd-type--display-1">Ripple</h2>
<div mdaRipple [ngStyle]="{width: '200px', height: '100px', background: '#00ccff'}"></div>
<div mdaRipple [ngStyle]="{width: '100px', height: '200px', background: '#cc00ff'}" mdaRippleColor="rgba(255, 255, 255, .3)"></div>
<div mdaRipple [ngStyle]="{width: '200px', height: '200px', background: '#ccff00'}"></div>

// preact/demo/src/components/demos/RippleDemo.tsx
import { h } from 'preact';
import { Ripple } from '@material-design/preact';

export function RippleDemo() {
    return <div>
        <h2 class="umd-type--display-1">Ripple</h2>
        <div style={{width: 200, height: 100, background: '#00ccff'}}>
            <Ripple />
        </div>
        <div style={{width: 100, height: 200, background: '#cc00ff'}}>
            <Ripple colour="rgba(255, 255, 255, .3)" />
        </div>
        <div style={{width: 200, height: 200, background: '#ccff00'}}>
            <Ripple />
        </div>
    </div>
}
