// angular/demo/src/app/demos/textfield/textfield-demo.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'textfield-demo',
    templateUrl: './textfield-demo.component.html',
})
export class TextFieldDemoComponent {
}

<h2 class="umd-type--display-1">Text Fields</h2>
<div>
    <mda-textfield label="Label text"></mda-textfield>
    <mda-textfield label="Disabled input" disabled value="This should be disabled"></mda-textfield>
</div>

// preact/demo/src/components/demos/TextFieldDemo.tsx
import { h } from 'preact';
import { TextField } from '@material-design/preact';

export function TextFieldDemo() {
    return <div>
        <h2 class="umd-type--display-1">Text Fields</h2>
        <div>
            <TextField label="Label text" />
            <TextField label="Disabled input" disabled value="This should be disabled" />
        </div>
    </div>
}
