// angular/demo/src/app/demos/toolbar/toolbar-demo.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'toolbar-demo',
    templateUrl: './toolbar-demo.component.html',
})
export class ToolbarDemoComponent {
}

<h2 class="umd-type--display-1">Toolbars</h2>
<div>
    <h3 class="umd-type--headline">App</h3>
    <mda-toolbar>App Toolbar</mda-toolbar>
</div>

// preact/demo/src/components/demos/ToolbarDemo.tsx
import { h } from 'preact';
import { Toolbar } from '@material-design/preact';

export function ToolbarDemo() {
    return <div>
        <h2 class="umd-type--display-1">Toolbars</h2>
        <div>
            <h3 class="umd-type--headline">App</h3>
            <Toolbar>App Toolbar</Toolbar>
        </div>
    </div>
}
