// preact/src/components/Button.tsx
import { h, Component } from 'preact';

import { Ripple } from './Ripple';

export interface ButtonProps {
    type?: 'button' | 'submit';
    dense?: boolean;
    flat?: boolean;
    disabled?: boolean;
    icon?: boolean;
    fab?: boolean;
    miniFab?: boolean;
    variant?: string;

    onClick?: JSX.MouseEventHandler;
}

export class Button extends Component<ButtonProps, {}> {
    static defaultProps: ButtonProps = {
        type: 'button',
        dense: false,
        flat: false,
        disabled: false,
        icon: false,
        fab: false,
        miniFab: false,
        variant: 'default',
    };

    public render() {
        const {
            children,
            type,
            dense,
            flat,
            disabled,
            icon,
            fab,
            miniFab,
            variant,

            onClick,
        } = this.props;

        const btnClasses = ['umd-button'];

        if (dense) {
            btnClasses.push('umd-button--dense');
        }

        if (flat) {
            btnClasses.push('umd-button--flat');
        }

        if (disabled) {
            btnClasses.push('umd-button--disabled');
        }

        if (icon) {
            btnClasses.push('umd-button--icon');
        }

        if (fab) {
            btnClasses.push('umd-button--fab');
        }

        if (miniFab) {
            btnClasses.push('umd-button--mini-fab');
        }

        return (
            <button
                class={btnClasses.join(' ')}
                type={type}
                onClick={onClick}
                data-umd-variant={variant}>
                <div class="umd-button__inner">
                    {children}
                    <Ripple />
                </div>
            </button>
        )
    }
}

// angular/src/components/button.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
    selector: '[mdaButton],[mdaRaisedButton]',
    template: `
        <div class="umd-button__inner" mdaRipple>
            <ng-content></ng-content>
        </div>
    `
})
export class MdaButton {
    @HostBinding('class.umd-button')
    public _ = true;

    @Input()
    public set mdaRaisedButton(raised: boolean) {
        this.isFlat = raised === false || raised === null;
    }

    @Input()
    public set dense(dense: boolean) {
        this.isDense = dense !== false && dense !== null;
    }

    @Input()
    public set icon(icon: boolean) {
        this.isIcon = icon !== false && icon !== null;
    }

    @Input()
    public set fab(fab: boolean) {
        this.isFab = fab !== false && fab !== null;
    }

    @Input()
    public set miniFab(fab: boolean) {
        this.isMiniFab = fab !== false && fab !== null;
    }

    @Input()
    public set disabled(disabled: boolean) {
        this.isDisabled = disabled !== false && disabled !== null;
    }

    @HostBinding('class.umd-button--flat')
    public isFlat = true;

    @HostBinding('class.umd-button--dense')
    public isDense = false;

    @HostBinding('class.umd-button--disabled')
    public isDisabled = false;

    @HostBinding('class.umd-button--icon')
    public isIcon = false;

    @HostBinding('class.umd-button--fab')
    public isFab = false;

    @HostBinding('class.umd-button--mini-fab')
    public isMiniFab = false;

    @Input()
    @HostBinding('attr.data-umd-variant')
    public mdaVariant: string = 'default';
}
