// preact/src/components/Card/Card.tsx
import { h, Component } from 'preact';

export class Card extends Component<{ fill?: boolean, style?: string | { [key: string]: any } }, {}> {
    public render() {
        const { children, fill, style } = this.props;

        const classes = ['umd-card'];
        fill && classes.push('umd-card--full-width');

        return <div class={classes.join(' ')} style={style}>{children}</div>;
    }
}

export class CardText extends Component<{}, {}> {
    public render() {
        const { children } = this.props;
        return <div class="umd-card-text umd-card--includes-padding">{children}</div>;
    }
}

export class CardMedia extends Component<{}, {}> {
    public render() {
        const { children } = this.props;
        return <div class="umd-card-media">{children}</div>;
    }
}

export class CardTitle extends Component<{}, {}> {
    public render() {
        const { children } = this.props;
        return <div class="umd-card-title umd-card--includes-padding">{children}</div>;
    }
}

export class CardSubtitle extends Component<{}, {}> {
    public render() {
        const { children } = this.props;
        return <div class="umd-card-subtitle umd-card--includes-padding">{children}</div>;
    }
}

export class CardActions extends Component<{ vertical?: boolean }, {}> {
    public render() {
        const { children, vertical } = this.props;
        const classes = ['umd-card-actions'];

        if (vertical) {
            classes.push('umd-card-actions--vertical');
        }

        return <div class={classes.join(' ')}>{children}</div>;
    }
}

export class CardMediaArea extends Component<{ media: JSX.Element }, {}> {
    public render() {
        const { children, media } = this.props;
        return <div class="umd-card-media-area">
            <div class="umd-card-media-area__content">{children}</div>
            <div class="umd-card-media-area__media">{media}</div>
        </div>;
    }
}

export * from './CardHeader';

// angular/src/components/card.ts
import { Component, Directive, HostBinding, Input, ElementRef } from '@angular/core';
import { HostClasses } from '../core/classes';

@HostClasses('umd-card')
@Directive({
    selector: 'mda-card'
})
export class MdaCard {
    @HostBinding('class.umd-card--full-width')
    public isFullWidth = false;

    @Input()
    public set fill(fill: boolean) {
        this.isFullWidth = fill !== false && fill !== null;
    }

    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-text umd-card--includes-padding')
@Directive({
    selector: 'mda-card-text'
})
export class MdaCardText {
    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-media')
@Directive({
    selector: 'mda-card-media'
})
export class MdaCardMedia {
    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-title umd-card--includes-padding')
@Directive({
    selector: 'mda-card-title'
})
export class MdaCardTitle {
    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-subtitle umd-card--includes-padding')
@Directive({
    selector: 'mda-card-subtitle'
})
export class MdaCardSubtitle {
    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-actions')
@Directive({
    selector: 'mda-card-actions',
})
export class MdaCardActions {
    @Input()
    public set vertical(vertical: boolean) {
        this.isVertical = vertical !== false && vertical !== null;
    }

    @HostBinding('class.umd-card-actions--vertical')
    public isVertical = false;

    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-media-area')
@Component({
    selector: 'mda-card-media-area',
    template: `
        <div class="umd-card-media-area__content">
            <ng-content></ng-content>
        </div>
        <div class="umd-card-media-area__media">
            <ng-content select="[media]"></ng-content>
        </div>
    `
})
export class MdaCardMediaArea {
    constructor(private elementRef: ElementRef) {}
}

@HostClasses('umd-card-header umd-card--includes-padding')
@Component({
    selector: 'mda-card-header',
    template: `
        <img class="umd-card-header__avatar" [src]="avatar" *ngIf="avatar">
        <div class="umd-card-header__titles">
            <h1>{{ title }}</h1>
            <h2>{{ subtitle }}</h2>
        </div>
    `
})
export class MdaCardHeader {
    @Input()
    public avatar: string;

    @Input()
    public title: string;

    @Input()
    public subtitle: string;

    constructor(private elementRef: ElementRef) {}
}
