// preact/src/components/Chip.tsx
import { h, Component } from 'preact';

export interface ChipProps {
    image?: string;
}

export class Chip extends Component<ChipProps, {}> {
    public render() {
        const {
            image,
            children
        } = this.props;

        return <div class="umd-chip">
            { image && <img src={image} /> }
            <span class="umd-chip__text">{children}</span>
        </div>;
    }
}

// angular/src/components/chip.ts
import { Component, HostBinding, Input } from '@angular/core';

@Component({
    selector: 'mda-chip',
    template: `
        <img [src]="image" *ngIf="image">
        <span class="umd-chip__text"><ng-content></ng-content></span>
    `
})
export class MdaChip {
    @HostBinding('class.umd-chip')
    public _ = true;

    @Input()
    public image: string;
}
