// preact/demo/src/components/demos/CardDemo.tsx
import { h } from 'preact';
import {
    Button,
    Card,
    CardHeader,
    CardText,
    CardMedia,
    CardMediaArea,
    CardTitle,
    CardSubtitle,
    CardActions
} from '@material-design/preact';

export function CardDemo() {
    return <div>
        <h2 class="umd-type--display-1">Cards</h2>
        <div>
            <h3 class="umd-type--headline">Simple</h3>
            <Card>
                <CardTitle>Title goes here</CardTitle>
                <CardSubtitle>Subtitle here</CardSubtitle>
                <CardText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</CardText>
            </Card>
        </div>
        <div>
            <h3 class="umd-type--headline">Header</h3>
            <Card>
                <CardHeader avatar="http://placehold.it/128x128" title="Title" subtitle="Subhead" />
                <CardText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</CardText>
            </Card>
        </div>
        <div>
            <h3 class="umd-type--headline">Actions</h3>
            <div style="display: flex; align-items: flex-start;">
                <Card style="margin-right: 16px;">
                    <CardTitle>Title goes here</CardTitle>
                    <CardText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</CardText>
                    <CardActions>
                        <Button flat>Action 1</Button>
                        <Button flat>Action 2</Button>
                    </CardActions>
                </Card>
                <Card>
                    <CardTitle>Title goes here</CardTitle>
                    <CardText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</CardText>
                    <CardActions vertical>
                        <Button flat>Action 1</Button>
                        <Button flat>Action 2</Button>
                    </CardActions>
                </Card>
            </div>
        </div>
        <div>
            <h3 class="umd-type--headline">Media</h3>
            <Card>
                <CardMedia>
                    <img src="http://placehold.it/640x360" />
                </CardMedia>
                <CardText>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</CardText>
            </Card>
        </div>
        <div>
            <h3 class="umd-type--headline">Media Area</h3>
            <Card>
                <CardMediaArea media={<img src="http://placehold.it/120x120" />}>
                    <CardTitle>Title here</CardTitle>
                    <CardSubtitle>Subtitle here</CardSubtitle>
                </CardMediaArea>
                <CardActions>
                    <Button flat>Action 1</Button>
                    <Button flat>Action 2</Button>
                </CardActions>
            </Card>
        </div>
    </div>
}

// angular/demo/src/app/demos/card/card-demo.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'card-demo',
    templateUrl: './card-demo.component.html',
})
export class CardDemoComponent {
}

<h2 class="umd-type--display-1">Cards</h2>
<div>
    <h3 class="umd-type--headline">Simple</h3>
    <mda-card>
        <mda-card-title>Title goes here</mda-card-title>
        <mda-card-subtitle>Subtitle here</mda-card-subtitle>
        <mda-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</mda-card-text>
    </mda-card>
</div>
<div>
    <h3 class="umd-type--headline">Header</h3>
    <mda-card>
        <mda-card-header avatar="http://placehold.it/128x128" title="Title" subtitle="Subhead"></mda-card-header>
        <mda-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</mda-card-text>
    </mda-card>
</div>
<div>
    <h3 class="umd-type--headline">Actions</h3>
    <div style="display: flex; align-items: flex-start;">
        <mda-card style="margin-right: 16px;">
            <mda-card-title>Title goes here</mda-card-title>
            <mda-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</mda-card-text>
            <mda-card-actions>
                <button mdaButton>Action 1</button>
                <button mdaButton>Action 2</button>
            </mda-card-actions>
        </mda-card>
        <mda-card>
            <mda-card-title>Title goes here</mda-card-title>
            <mda-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</mda-card-text>
            <mda-card-actions vertical>
                <button mdaButton>Action 1</button>
                <button mdaButton>Action 2</button>
            </mda-card-actions>
        </mda-card>
    </div>
</div>
<div>
    <h3 class="umd-type--headline">Media</h3>
    <mda-card>
        <mda-card-media>
            <img src="http://placehold.it/640x360">
        </mda-card-media>
        <mda-card-text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et nisl sit amet tellus fermentum iaculis.</mda-card-text>
    </mda-card>
</div>
<div>
    <h3 class="umd-type--headline">Media Area</h3>
    <mda-card>
        <mda-card-media-area>
            <img media src="http://placehold.it/120x120">
            <mda-card-title>Title here</mda-card-title>
            <mda-card-subtitle>Subtitle here</mda-card-subtitle>
        </mda-card-media-area>
        <mda-card-actions>
            <button mdaButton>Action 1</button>
            <button mdaButton>Action 2</button>
        </mda-card-actions>
    </mda-card>
</div>
