// preact/demo/src/components/App.tsx
import { h, Component } from 'preact';
import { Toolbar, Content } from '@material-design/preact';

import { ButtonDemo } from './demos/ButtonDemo';
import { CardDemo } from './demos/CardDemo';
import { ChipDemo } from './demos/ChipDemo';
import { DialogDemo } from './demos/DialogDemo';
import { IconDemo } from './demos/IconDemo';
import { RippleDemo } from './demos/RippleDemo';
import { TextFieldDemo } from './demos/TextFieldDemo';
import { ToolbarDemo } from './demos/ToolbarDemo';
import { TypographyDemo } from './demos/TypographyDemo';

export class App extends Component<{}, {}> {
    public render() {
        return (
            <div>
                <Toolbar>Preact Material Design</Toolbar>
                <Content>
                    <p>A set of components for Preact that conform to the material design guidlines.</p>
                    <ButtonDemo />
                    <CardDemo />
                    <ChipDemo />
                    <DialogDemo />
                    <IconDemo />
                    <RippleDemo />
                    <TextFieldDemo />
                    <ToolbarDemo />
                    <TypographyDemo />
                </Content>
            </div>
        )
    }
}

// angular/demo/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
    selector: 'amd-app',
    templateUrl: './app.component.html',
    styles: [``]
})
export class AppComponent {
}

<mda-toolbar>Angular Material Design</mda-toolbar>
<mda-content>
    <p>A set of components for Angular that conform to the material design guidlines.</p>
    <button-demo></button-demo>
    <card-demo></card-demo>
    <chip-demo></chip-demo>
    <dialog-demo></dialog-demo>
    <icon-demo></icon-demo>
    <ripple-demo></ripple-demo>
    <textfield-demo></textfield-demo>
    <toolbar-demo></toolbar-demo>
    <typography-demo></typography-demo>
</mda-content>
