// preact/demo/src/components/demos/DialogDemo.tsx
import { h, Component } from 'preact';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle } from '@material-design/preact';

export class DialogDemo extends Component<{}, {}> {
    dialog: Dialog;

    public render() {
        return <div>
            <h2 class="umd-type--display-1">Dialogs</h2>
            <div>
                <Button onClick={() => this.dialog.show()}>Show Dialog</Button>
                <Dialog ref={dialog => this.dialog = dialog}>
                    <DialogTitle>Dialog Title</DialogTitle>
                    <DialogContent>This is the dialog's content</DialogContent>
                    <DialogActions>
                        <Button flat onClick={() => this.dialog.hide()}>Cancel</Button>
                        <Button flat>Ok</Button>
                    </DialogActions>
                </Dialog>
            </div>
        </div>
    }
}

// angular/demo/src/app/demos/dialog/dialog-demo.component.ts
import { MdaDialog, MdaDialogRef } from '@material-design/angular';
import { Component } from '@angular/core';

@Component({
    selector: 'dialog-demo',
    templateUrl: './dialog-demo.component.html',
})
export class DialogDemoComponent {
    constructor(private dialog: MdaDialog) {
    }

    public showDialog() {
        this.dialog.open(DemoDialog);
    }
}

@Component({
    selector: 'demo-dialog',
    template: `
        <mda-dialog-title>Dialog Title</mda-dialog-title>
        <mda-dialog-content>This is the dialog's content</mda-dialog-content>
        <mda-dialog-actions>
            <button mdaButton (click)="dialogRef.close()">Cancel</button>
            <button mdaButton>Ok</button>
        </mda-dialog-actions>
    `
})
export class DemoDialog {
    constructor(public dialogRef: MdaDialogRef) {
    }
}

<h2 class="umd-type--display-1">Dialogs</h2>
<div>
    <button mdaRaisedButton (click)="showDialog()">Show Dialog</button>
</div>
